name: Publish to pub.dev

on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish:
    name: Publish

    permissions:
      id-token: write # Required for authentication using OIDC
      contents: read # Required to checkout the repo

    environment: pub.dev
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v4

      - name: Setup Dart
        uses: dart-lang/setup-dart@e51d8e571e22473a2ddebf0ef8a2123f0ab2c02c # v1.6.5
        with:
          sdk: stable

      - name: Install dependencies
        run: dart pub get

      - name: Publish to pub.dev
        run: dart pub publish --force
